// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3532.PiranhaEnergy;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainRightMotor;
    public static SpeedController driveTrainLeftMotor;
    public static RobotDrive driveTrainRobotDrive21;
    public static SpeedController canonPushDisk;
    public static SpeedController canonLoadDisk;
    public static SpeedController canonMotorFront;
    public static SpeedController canonMotorBack;
    public static SpeedController canonCanonHeightMotor2;
    public static Servo cameraMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightMotor = new Victor(1, 1);
	LiveWindow.addActuator("DriveTrain", "RightMotor", (Victor) driveTrainRightMotor);
        
        driveTrainLeftMotor = new Victor(1, 2);
	LiveWindow.addActuator("DriveTrain", "LeftMotor ", (Victor) driveTrainLeftMotor);
        
        driveTrainRobotDrive21 = new RobotDrive(driveTrainRightMotor, driveTrainLeftMotor);
	
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(1.0);
        
        canonPushDisk = new Victor(1, 6);
	LiveWindow.addActuator("Canon", "PushDisk", (Victor) canonPushDisk);
        
        canonLoadDisk = new Victor(1, 5);
	LiveWindow.addActuator("Canon", "LoadDisk", (Victor) canonLoadDisk);
        
        canonMotorFront = new Victor(1, 3);
	LiveWindow.addActuator("Canon", "MotorFront", (Victor) canonMotorFront);
        
        canonMotorBack = new Victor(1, 4);
	LiveWindow.addActuator("Canon", "MotorBack", (Victor) canonMotorBack);
        
        canonCanonHeightMotor2 = new Victor(1, 7);
	LiveWindow.addActuator("Canon", "CanonHeightMotor2", (Victor) canonCanonHeightMotor2);
        
        cameraMotor = new Servo(1, 8);
	LiveWindow.addActuator("Camera", "Motor", cameraMotor);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
