// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3532.PiranhaEnergy.subsystems;
import org.usfirst.frc3532.PiranhaEnergy.RobotMap;
import org.usfirst.frc3532.PiranhaEnergy.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Camera extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Servo motor = RobotMap.cameraMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    double angle = 0.0;
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
    }
    
    public void setAngle( double newAngle) {
        motor.setAngle(newAngle);
        System.out.print("Setting camera angle to ");
        System.out.println(newAngle);
     
    }
    public void raise() {
        angle += 5.0;
        setAngle(angle);
    }
    public void lower() {
        angle -= 5.0;
        setAngle(angle);
    }
}
